<?php
try {
    throw new Exception('Error horroroso');
    echo "Se ha saltado la excepciÃ³n.";
} catch (Exception $e) {
    echo "Se ha provocado el siguiente error: " . $e->getMessage();
}
